name: JIB container publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: JIB container build and publish
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.5
        with:
          # Use docker.io for Docker Hub if empty
          REGISTRY: 
          # github.repository as <your-account>/<your-repo>
          IMAGE_NAME: registry.hub.docker.com/rashudey/google-jib-image-example
          # Tag name of the image to publish
          tag-name: latest
          # Username to login to registry
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # Password to login to registry
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          java-version: 17
